#!/usr/bin/env bash

run() {
	cmd=$*
	sleep 5
	echo "starting command!"
	exec $cmd
}

if [ $# -eq 0 ]; then
	>&2 echo "usage: nthr <what> <command> <command_args>"
	>&2 echo "works best with disabled ASLR, i.e."
	>&2 echo "  echo 0 | sudo tee /proc/sys/kernel/randomize_va_space"
	>&2 echo "or"
	>&2 echo "  setarch \$(uname -m) -R <cmd>"
	exit 1
fi

if [ "$EUID" -eq 0 ]; then
	echo "Do not run me as root! I will run sudo when needed."
	exit 1
fi

tmpfile=$(mktemp /tmp/wtcf-log.XXXXXX)

probe=$1
shift
cmd=$*

if ! sudo bpftrace -l "$probe"; then
	exit 1
fi

echo "tracing $probe tracepoint"
echo "raw data at: $tmpfile"

(run $cmd ) &
pid=$!

sudo -E "$(which bpftrace)" -e '

tracepoint:sched:sched_process_exec /pid == $1 && !@init/ {
	@init = 1;
}

'"$probe"' /pid == $1 && @init/ {
	print(ustack)
}

tracepoint:sched:sched_process_exit /tid == $1 && @init/ {
	exit();
}

END {
	clear(@init);
}
' $pid | tee "$tmpfile" >/dev/null

wait $pid

echo "parsing bpf data..."

sed -i '1d' "$tmpfile"

python3 <<EOF
#!/usr/bin/env python3
import sys
from collections import defaultdict


filename="$tmpfile"
dic = defaultdict(int)

ss=""
with open(filename) as file:
	for line in file:
		if line.strip():
			ss = ss + line
		elif ss:
			dic[ss] += 1
			ss = ""


for key, val in sorted(dic.items(), key=lambda item: item[1]):
	print(val)
	print(key)
	print("\n")
EOF

#rm -f $tmpfile
