#!/usr/bin/env python3
"""
Plot multiple memory bandwidth measurements in a single figure
Combines data from multiple CSV files generated by mem_bandwidth_monitor.py
"""

import argparse
import sys
import matplotlib.pyplot as plt
import numpy as np
import csv
from pathlib import Path
import matplotlib as mpl

mpl.rcParams['pdf.fonttype'] = 42  # TrueType

class BandwidthPlotter:
    def __init__(self):
        self.datasets = []
        self.labels = []
        
    def load_csv(self, csv_file, label):
        """
        Load bandwidth data from CSV file
        Returns True if successful, False otherwise
        """
        try:
            times = []
            reads = []
            writes = []
            totals = []
            
            with open(csv_file, 'r') as f:
                reader = csv.DictReader(f)
                for row in reader:
                    times.append(float(row['Time(s)']))
                    reads.append(float(row['Read(GB/s)']))
                    writes.append(float(row['Write(GB/s)']))
                    totals.append(float(row['Total(GB/s)']))
            
            if not times:
                print(f"Warning: No data found in {csv_file}")
                return False
            
            self.datasets.append({
                'time': np.array(times),
                'read': np.array(reads),
                'write': np.array(writes),
                'total': np.array(totals),
                'file': csv_file
            })
            self.labels.append(label)
            
            print(f"Loaded {len(times)} samples from {csv_file}")
            return True
            
        except FileNotFoundError:
            print(f"Error: File not found: {csv_file}")
            return False
        except Exception as e:
            print(f"Error loading {csv_file}: {e}")
            return False
    
    def plot_combined(self, output_file='combined_bandwidth.png', title=None, 
                     plot_type='total', colors=None, linestyles=None, zoom_range=None, 
                     zoom_loc='upper right', zoom_size=35, fontsize=12, no_titles=False, 
                     figsize=None, legend_loc='best', legend_ncol=1, no_legend=False, 
                     export_legend=None, show=True):
        """
        Create combined plot of all loaded datasets
        
        Args:
            output_file: Output filename for the plot
            title: Custom title for the plot
            plot_type: 'total', 'read', 'write', or 'all'
            colors: List of color names/hex codes, or None for default palette
            linestyles: List of line styles ('-', '--', '-.', ':'), or None for all solid
            zoom_range: Tuple of (start_time, end_time) for zoom inset, or None
            zoom_loc: Location string ('upper right', etc.) or tuple (x, y, width, height) in axes coords
            zoom_size: Size of zoom inset as percentage (ignored if zoom_loc is tuple)
            fontsize: Base font size for all text elements (default: 12)
            no_titles: If True, suppress main title and subplot titles (default: False)
            figsize: Tuple of (width, height) in inches, or None for defaults
            legend_loc: Legend location string or tuple (x, y) in axes coordinates (default: 'best')
            legend_ncol: Number of columns in the legend (default: 1)
            no_legend: If True, hide the legend completely (default: False)
            export_legend: If provided, export legend to this file (default: None)
            show: Whether to display the plot interactively
        """
        if not self.datasets:
            print("Error: No data to plot!")
            return
        
        # Determine number of subplots based on plot_type
        if plot_type == 'all':
            default_figsize = (14, 12)
            fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=figsize if figsize else default_figsize)
            axes = [ax1, ax2, ax3]
        else:
            default_figsize = (14, 6)
            fig, ax = plt.subplots(1, 1, figsize=figsize if figsize else default_figsize)
            axes = [ax]
        
        # Color palette - use custom if provided, otherwise use default
        if colors:
            color_list = colors
        else:
            color_list = plt.cm.tab10(np.linspace(0, 1, len(self.datasets)))
        
        # Line styles - use custom if provided, otherwise all solid
        if linestyles:
            linestyle_list = linestyles
        else:
            linestyle_list = ['-'] * len(self.datasets)  # All solid lines
        
        # Main title - only if not suppressed
        if not no_titles:
            if title:
                fig.suptitle(title, fontsize=fontsize*1.33, fontweight='bold', y=0.995)
            else:
                fig.suptitle('Memory Bandwidth Comparison', fontsize=fontsize*1.33, fontweight='bold', y=0.995)
        
        # Helper function to add zoom inset
        def add_zoom_inset(ax, datasets, labels, colors, linestyles, data_key):
            """Add a zoomed inset subplot showing a time range"""
            from mpl_toolkits.axes_grid1.inset_locator import inset_axes
            
            # Check if zoom_loc is a tuple of coordinates or a location string
            if isinstance(zoom_loc, tuple) and len(zoom_loc) == 4:
                # Custom coordinates: (x, y, width, height) in axes coordinates (0-1)
                x, y, width, height = zoom_loc
                axins = ax.inset_axes([x, y, width, height])
            else:
                # Map location strings to matplotlib loc codes
                loc_map = {
                    'upper right': 'upper right',
                    'upper left': 'upper left',
                    'lower right': 'lower right',
                    'lower left': 'lower left',
                    'center': 'center',
                    'center right': 'center right',
                    'center left': 'center left',
                    'upper center': 'upper center',
                    'lower center': 'lower center'
                }
                
                loc = loc_map.get(zoom_loc, 'upper right')
                size_str = f"{zoom_size}%"
                
                # Create inset axes
                axins = inset_axes(ax, width=size_str, height=size_str, loc=loc,
                                  bbox_to_anchor=(0, 0, 1, 1), bbox_transform=ax.transAxes)
            
            # Plot data in inset with zoom range
            for data, label, color, linestyle in zip(datasets, labels, colors, linestyles):
                mask = (data['time'] >= zoom_range[0]) & (data['time'] <= zoom_range[1])
                axins.plot(data['time'][mask], data[data_key][mask], 
                          linewidth=2, color=color, linestyle=linestyle, alpha=0.8)
            
            # Set zoom range for x-axis
            axins.set_xlim(zoom_range[0], zoom_range[1])
            
            # Auto-scale y-axis to zoomed data for better detail
            all_values = []
            for data in datasets:
                mask = (data['time'] >= zoom_range[0]) & (data['time'] <= zoom_range[1])
                all_values.extend(data[data_key][mask])
            
            if all_values:
                y_min, y_max = min(all_values), max(all_values)
                y_margin = (y_max - y_min) * 0.15  # 15% margin
                axins.set_ylim(y_min - y_margin, y_max + y_margin)
            
            # Style the inset
            axins.grid(True, alpha=0.3, linewidth=0.5)
            axins.tick_params(labelsize=fontsize*0.75)
            
            # Set inset background to whitesmoke (opaque)
            axins.set_facecolor('whitesmoke')
            
            # Add whitesmoke rectangle on main plot showing zoom region
            from matplotlib.patches import Rectangle
            y_min_main, y_max_main = ax.get_ylim()
            rect = Rectangle((zoom_range[0], y_min_main), 
                           zoom_range[1] - zoom_range[0],
                           y_max_main - y_min_main,
                           linewidth=1.5, edgecolor='gray', facecolor='whitesmoke',
                           alpha=0.3, zorder=0)
            ax.add_patch(rect)
            
            return axins
        
        # Plot based on type
        if plot_type in ['total', 'all']:
            ax_idx = 0 if plot_type == 'all' else 0
            ax = axes[ax_idx]
            
            for data, label, color, linestyle in zip(self.datasets, self.labels, color_list, linestyle_list):
                ax.plot(data['time'], data['total'], 
                       label=label, linewidth=2, color=color, linestyle=linestyle, alpha=0.8)
            
            ax.set_xlabel('Time (seconds)', fontsize=fontsize)
            ax.set_ylabel('Total Bandwidth (GB/s)', fontsize=fontsize)
            if not no_titles:
                ax.set_title('Total Memory Bandwidth', fontsize=fontsize*1.17, fontweight='bold')
            
            # Add legend unless suppressed
            if not no_legend:
                # Handle legend location (string or tuple)
                if isinstance(legend_loc, tuple):
                    ax.legend(loc=legend_loc, fontsize=fontsize*0.83, ncol=legend_ncol,
                             bbox_to_anchor=legend_loc, bbox_transform=ax.transAxes)
                else:
                    ax.legend(loc=legend_loc, fontsize=fontsize*0.83, ncol=legend_ncol)
            
            ax.tick_params(labelsize=fontsize*0.92)
            ax.grid(True, alpha=0.3)
            
            # Add zoom inset if requested
            if zoom_range:
                add_zoom_inset(ax, self.datasets, self.labels, color_list, linestyle_list, 'total')
        
        if plot_type in ['read', 'all']:
            ax_idx = 1 if plot_type == 'all' else 0
            ax = axes[ax_idx]
            
            for data, label, color, linestyle in zip(self.datasets, self.labels, color_list, linestyle_list):
                ax.plot(data['time'], data['read'], 
                       label=label, linewidth=2, color=color, linestyle=linestyle, alpha=0.8)
            
            ax.set_xlabel('Time (seconds)', fontsize=fontsize)
            ax.set_ylabel('Read Bandwidth (GB/s)', fontsize=fontsize)
            if not no_titles:
                ax.set_title('Read Memory Bandwidth', fontsize=fontsize*1.17, fontweight='bold')
            
            # Add legend unless suppressed
            if not no_legend:
                # Handle legend location (string or tuple)
                if isinstance(legend_loc, tuple):
                    ax.legend(loc=legend_loc, fontsize=fontsize*0.83, ncol=legend_ncol,
                             bbox_to_anchor=legend_loc, bbox_transform=ax.transAxes)
                else:
                    ax.legend(loc=legend_loc, fontsize=fontsize*0.83, ncol=legend_ncol)
            
            ax.tick_params(labelsize=fontsize*0.92)
            ax.grid(True, alpha=0.3)
            
            # Add zoom inset if requested
            if zoom_range:
                add_zoom_inset(ax, self.datasets, self.labels, color_list, linestyle_list, 'read')
        
        if plot_type in ['write', 'all']:
            ax_idx = 2 if plot_type == 'all' else 0
            ax = axes[ax_idx]
            
            for data, label, color, linestyle in zip(self.datasets, self.labels, color_list, linestyle_list):
                ax.plot(data['time'], data['write'], 
                       label=label, linewidth=2, color=color, linestyle=linestyle, alpha=0.8)
            
            ax.set_xlabel('Time (seconds)', fontsize=fontsize)
            ax.set_ylabel('Write Bandwidth (GB/s)', fontsize=fontsize)
            if not no_titles:
                ax.set_title('Write Memory Bandwidth', fontsize=fontsize*1.17, fontweight='bold')
            
            # Add legend unless suppressed
            if not no_legend:
                # Handle legend location (string or tuple)
                if isinstance(legend_loc, tuple):
                    ax.legend(loc=legend_loc, fontsize=fontsize*0.83, ncol=legend_ncol,
                             bbox_to_anchor=legend_loc, bbox_transform=ax.transAxes)
                else:
                    ax.legend(loc=legend_loc, fontsize=fontsize*0.83, ncol=legend_ncol)
            
            ax.tick_params(labelsize=fontsize*0.92)
            ax.grid(True, alpha=0.3)
            
            # Add zoom inset if requested
            if zoom_range:
                add_zoom_inset(ax, self.datasets, self.labels, color_list, linestyle_list, 'write')
        
        plt.tight_layout(rect=[0, 0, 1, 0.99])  # Leave space for suptitle
        plt.savefig(output_file, dpi=150, bbox_inches='tight')
        print(f"\nPlot saved to: {output_file}")
        
        # Export standalone legend if requested
        if export_legend:
            self._export_legend(export_legend, fontsize, legend_ncol, colors, linestyles)
        
        if show:
            plt.show()
    
    def _export_legend(self, output_file, fontsize, ncol, colors, linestyles):
        """
        Export legend as a standalone figure with tight trimming
        
        Args:
            output_file: Output filename for legend
            fontsize: Font size for legend text
            ncol: Number of columns
            colors: Color list
            linestyles: Linestyle list
        """
        # Create a new figure just for the legend with minimal size
        fig_legend = plt.figure(figsize=(ncol * 2, 0.5))
        ax_legend = fig_legend.add_subplot(111)
        
        # Hide the axes completely
        ax_legend.axis('off')
        
        # Create dummy lines with the same styling as the plot
        color_list = colors if colors else plt.cm.tab10(np.linspace(0, 1, len(self.datasets)))
        linestyle_list = linestyles if linestyles else ['-'] * len(self.datasets)
        
        legend_handles = []
        for label, color, linestyle in zip(self.labels, color_list, linestyle_list):
            line = plt.Line2D([0], [0], color=color, linestyle=linestyle, 
                            linewidth=4, label=label)
            legend_handles.append(line)
        
        # Create legend with minimal padding
        legend = ax_legend.legend(handles=legend_handles, 
                                 loc='center',
                                 fontsize=fontsize*0.83,
                                 ncol=ncol,
                                 frameon=True,
                                 fancybox=False,
                                 shadow=False,
                                 borderpad=0.5,
                                 labelspacing=0.3,
                                 columnspacing=1.0,
                                 handlelength=2.0)
        
        # Get the legend bounding box and save with minimal margins
        # Use pad_inches=0.05 for very tight cropping
        fig_legend.canvas.draw()
        bbox = legend.get_window_extent()
        bbox_inches = bbox.transformed(fig_legend.dpi_scale_trans.inverted())
        
        # Expand slightly for better appearance (0.1 inches padding)
        bbox_inches = bbox_inches.expanded(1.05, 1.05)
        
        # Save with the tight bounding box
        fig_legend.savefig(output_file, dpi=150, bbox_inches=bbox_inches)
        print(f"Legend exported to: {output_file}")
        plt.close(fig_legend)
    
    def print_statistics(self):
        """Print summary statistics for all datasets"""
        if not self.datasets:
            return
        
        print("\n" + "="*80)
        print("SUMMARY STATISTICS")
        print("="*80)
        
        for data, label in zip(self.datasets, self.labels):
            print(f"\n{label}:")
            print(f"  Duration:        {data['time'][-1]:.2f} seconds")
            print(f"  Samples:         {len(data['time'])}")
            print(f"  Read BW (avg):   {np.mean(data['read']):.2f} GB/s")
            print(f"  Read BW (max):   {np.max(data['read']):.2f} GB/s")
            print(f"  Write BW (avg):  {np.mean(data['write']):.2f} GB/s")
            print(f"  Write BW (max):  {np.max(data['write']):.2f} GB/s")
            print(f"  Total BW (avg):  {np.mean(data['total']):.2f} GB/s")
            print(f"  Total BW (max):  {np.max(data['total']):.2f} GB/s")
            print(f"  Total BW (std):  {np.std(data['total']):.2f} GB/s")
        
        print("="*80)
    
    def create_comparison_table(self, output_file='comparison_table.png'):
        """Create a side-by-side comparison table"""
        if not self.datasets:
            return
        
        fig, ax = plt.subplots(figsize=(12, max(4, len(self.datasets) * 0.8)))
        ax.axis('off')
        
        # Prepare table data
        table_data = []
        headers = ['Configuration', 'Avg Total\n(GB/s)', 'Max Total\n(GB/s)', 
                  'Avg Read\n(GB/s)', 'Avg Write\n(GB/s)', 'Std Dev\n(GB/s)']
        
        for data, label in zip(self.datasets, self.labels):
            row = [
                label,
                f"{np.mean(data['total']):.2f}",
                f"{np.max(data['total']):.2f}",
                f"{np.mean(data['read']):.2f}",
                f"{np.mean(data['write']):.2f}",
                f"{np.std(data['total']):.2f}"
            ]
            table_data.append(row)
        
        # Create table
        table = ax.table(cellText=table_data,
                        colLabels=headers,
                        cellLoc='center',
                        loc='center',
                        bbox=[0, 0, 1, 1])
        
        table.auto_set_font_size(False)
        table.set_fontsize(10)
        table.scale(1, 2)
        
        # Style header
        for i in range(len(headers)):
            table[(0, i)].set_facecolor('#40466e')
            table[(0, i)].set_text_props(weight='bold', color='white')
        
        # Alternate row colors
        for i in range(1, len(table_data) + 1):
            for j in range(len(headers)):
                if i % 2 == 0:
                    table[(i, j)].set_facecolor('#f0f0f0')
        
        plt.title('Memory Bandwidth Comparison Summary', 
                 fontsize=14, fontweight='bold', pad=20)
        plt.savefig(output_file, dpi=150, bbox_inches='tight')
        print(f"Comparison table saved to: {output_file}")


def main():
    parser = argparse.ArgumentParser(
        description='Plot multiple memory bandwidth CSV files in one figure',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Compare two configurations
  python plot_bandwidth.py baseline.csv oversub.csv -l "Baseline,2x Oversubscription"
  
  # With custom colors
  python plot_bandwidth.py run1.csv run2.csv run3.csv \\
      -l "1 thread,2 threads,4 threads" \\
      -c "red,blue,green"
  
  # With custom linestyles
  python plot_bandwidth.py baseline.csv oversub.csv \\
      -l "Baseline,Oversubscribed" \\
      --linestyles "solid,dashed"
  
  # Combine colors and linestyles
  python plot_bandwidth.py run1.csv run2.csv run3.csv \\
      -l "Config A,Config B,Config C" \\
      -c "steelblue,coral,seagreen" \\
      --linestyles "-,--,-."
  
  # With hex color codes
  python plot_bandwidth.py baseline.csv oversub.csv \\
      -l "Baseline,Oversubscribed" \\
      -c "#1f77b4,#ff7f0e" \\
      -o comparison.png
  
  # Custom output and title
  python plot_bandwidth.py run1.csv run2.csv run3.csv \\
      -l "Config A,Config B,Config C" \\
      -c "darkblue,darkred,darkgreen" \\
      -o comparison.png \\
      -t "Thread Scaling Analysis"
  
  # Plot only total bandwidth
  python plot_bandwidth.py *.csv -l "Run 1,Run 2,Run 3" --type total
  
  # Show all bandwidth types (read, write, total)
  python plot_bandwidth.py config*.csv \\
      -l "Config A,Config B" \\
      -c "steelblue,coral" \\
      --type all
  
  # Add zoom inset to highlight a specific time range
  python plot_bandwidth.py baseline.csv oversub.csv \\
      -l "Baseline,Oversubscribed" \\
      -c "steelblue,coral" \\
      --zoom "5.0,15.0"
  
  # Customize zoom location and size
  python plot_bandwidth.py run1.csv run2.csv \\
      -l "Config A,Config B" \\
      --zoom "10,20" \\
      --zoom-loc "lower right" \\
      --zoom-size 40
  
  # Use custom coordinates for precise positioning (x, y, width, height in 0-1 range)
  python plot_bandwidth.py baseline.csv oversub.csv \\
      -l "Baseline,Oversubscribed" \\
      --zoom "5,15" \\
      --zoom-loc "0.15,0.55,0.35,0.35"
  
  # Customize font size for publication
  python plot_bandwidth.py baseline.csv oversub.csv \\
      -l "Baseline,Oversubscribed" \\
      --fontsize 14 \\
      -o large_font.png
  
  # Set figure dimensions (width x height in inches)
  python plot_bandwidth.py baseline.csv oversub.csv \\
      -l "Baseline,Oversubscribed" \\
      --figsize "10,5" \\
      -o wide_figure.png
  
  # Tall figure for multiple subplots
  python plot_bandwidth.py baseline.csv oversub.csv \\
      -l "Baseline,Oversubscribed" \\
      --figsize "8,12" \\
      --type all
  
  # Position legend precisely
  python plot_bandwidth.py baseline.csv oversub.csv \\
      -l "Baseline,Oversubscribed" \\
      --legend-loc "upper left"
  
  # Custom legend coordinates (x, y in axes coords 0-1)
  python plot_bandwidth.py baseline.csv oversub.csv \\
      -l "Baseline,Oversubscribed" \\
      --legend-loc "0.5,0.95"
  
  # Hide legend completely
  python plot_bandwidth.py baseline.csv oversub.csv \\
      -l "Baseline,Oversubscribed" \\
      --no-legend
  
  # Horizontal legend with 2 columns
  python plot_bandwidth.py run1.csv run2.csv run3.csv run4.csv \\
      -l "1x,2x,4x,8x" \\
      --legend-ncol 2 \\
      --legend-loc "upper center"
  
  # Horizontal legend at bottom with 4 columns
  python plot_bandwidth.py cfg1.csv cfg2.csv cfg3.csv cfg4.csv \\
      -l "Config A,Config B,Config C,Config D" \\
      --legend-ncol 4 \\
      --legend-loc "lower center"
  
  # Export legend to separate file
  python plot_bandwidth.py run1.csv run2.csv run3.csv \\
      -l "Baseline,2x Oversub,4x Oversub" \\
      --export-legend "legend.png" \\
      --legend-ncol 3 \\
      --fontsize 12
  
  # Create plot without legend and export legend separately
  python plot_bandwidth.py baseline.csv oversub.csv \\
      -l "Baseline,Oversubscribed" \\
      --no-legend \\
      --export-legend "standalone_legend.png" \\
      -o plot.png
  
  # Suppress titles (keep only axis labels)
  python plot_bandwidth.py baseline.csv oversub.csv \\
      -l "Baseline,Oversubscribed" \\
      --no-titles \\
      -o no_titles.png
  
  # Generate comparison table
  python plot_bandwidth.py baseline.csv oversub.csv \\
      -l "Baseline,Oversubscribed" \\
      --table table.png

Note: Labels and colors must be comma-separated (no spaces unless quoted)
      Number of CSV files, labels, and colors (if provided) must match
        """
    )
    
    parser.add_argument('csv_files', nargs='+',
                       help='CSV files to plot (generated by mem_bandwidth_monitor.py)')
    parser.add_argument('-l', '--labels', type=str, required=True,
                       help='Comma-separated labels for each CSV file (e.g., "Baseline,2x Oversub,4x Oversub")')
    parser.add_argument('-c', '--colors', type=str, default=None,
                       help='Comma-separated color names or hex codes (e.g., "red,blue,green" or "#FF0000,#0000FF,#00FF00")')
    parser.add_argument('--linestyles', '--ls', type=str, default=None,
                       help='Comma-separated line styles (e.g., "solid,dashed,dashdot,dotted" or "-,--,-.,:")')
    parser.add_argument('-o', '--output', type=str, default='combined_bandwidth.png',
                       help='Output plot filename (default: combined_bandwidth.png)')
    parser.add_argument('-t', '--title', type=str, default=None,
                       help='Custom title for the plot (default: "Memory Bandwidth Comparison")')
    parser.add_argument('--type', type=str, default='total',
                       choices=['total', 'read', 'write', 'all'],
                       help='Type of bandwidth to plot (default: total)')
    parser.add_argument('--zoom', type=str, default=None,
                       help='Time range to zoom in as "start,end" (e.g., "5.0,10.0")')
    parser.add_argument('--zoom-loc', type=str, default='upper right',
                       help='Location of zoom inset: named position or "x,y,width,height" in axes coords (0-1). '
                            'Named: upper right, upper left, lower right, lower left, center, etc. '
                            'Custom: e.g., "0.6,0.6,0.35,0.35" for x=0.6, y=0.6, width=0.35, height=0.35')
    parser.add_argument('--zoom-size', type=int, default=35,
                       help='Size of zoom inset as percentage of plot (default: 35)')
    parser.add_argument('--fontsize', type=int, default=12,
                       help='Base font size for all text elements (default: 12)')
    parser.add_argument('--figsize', type=str, default=None,
                       help='Figure size as "width,height" in inches (e.g., "10,6" or "8,10"). '
                            'Default: 14,6 for single plot; 14,12 for --type all')
    parser.add_argument('--legend-loc', type=str, default='best',
                       help='Legend location: named position (best, upper right, upper left, lower right, '
                            'lower left, center, etc.) or custom coordinates "x,y" in axes coords (0-1). '
                            'Default: best')
    parser.add_argument('--legend-ncol', type=int, default=1,
                       help='Number of columns in the legend (default: 1)')
    parser.add_argument('--export-legend', type=str, default=None,
                       help='Export legend to a separate file (e.g., "legend.png")')
    parser.add_argument('--no-legend', action='store_true',
                       help='Hide the legend completely')
    parser.add_argument('--no-titles', action='store_true',
                       help='Suppress main title and subplot titles (keep axis labels)')
    parser.add_argument('--table', type=str, default=None,
                       help='Generate comparison table and save to this file')
    parser.add_argument('--no-plot', action='store_true',
                       help='Skip displaying the plot interactively')
    
    args = parser.parse_args()
    
    # Parse comma-separated labels
    labels = [label.strip() for label in args.labels.split(',')]
    
    # Parse comma-separated colors if provided
    colors = None
    if args.colors:
        colors = [color.strip() for color in args.colors.split(',')]
        # Validate number of colors matches number of files
        if len(colors) != len(args.csv_files):
            print(f"Error: Number of colors ({len(colors)}) must match number of CSV files ({len(args.csv_files)})")
            print(f"Colors provided: {colors}")
            print(f"CSV files: {len(args.csv_files)}")
            sys.exit(1)
    
    # Parse comma-separated linestyles if provided
    linestyles = None
    if args.linestyles:
        linestyles = [style.strip() for style in args.linestyles.split(',')]
        # Validate number of linestyles matches number of files
        if len(linestyles) != len(args.csv_files):
            print(f"Error: Number of linestyles ({len(linestyles)}) must match number of CSV files ({len(args.csv_files)})")
            print(f"Linestyles provided: {linestyles}")
            print(f"CSV files: {len(args.csv_files)}")
            sys.exit(1)
        # Validate linestyle values
        valid_styles = ['-', '--', '-.', ':', 'solid', 'dashed', 'dashdot', 'dotted']
        for style in linestyles:
            if style not in valid_styles:
                print(f"Error: Invalid linestyle '{style}'")
                print(f"Valid styles: {', '.join(valid_styles)}")
                sys.exit(1)
    
    # Parse zoom range if provided
    zoom_range = None
    zoom_loc_parsed = args.zoom_loc  # Default to string
    
    if args.zoom:
        try:
            zoom_parts = args.zoom.split(',')
            if len(zoom_parts) != 2:
                print(f"Error: Zoom range must be two values: 'start,end'")
                sys.exit(1)
            zoom_range = (float(zoom_parts[0].strip()), float(zoom_parts[1].strip()))
            if zoom_range[0] >= zoom_range[1]:
                print(f"Error: Zoom start time must be less than end time")
                sys.exit(1)
            print(f"Zoom range: {zoom_range[0]:.2f}s to {zoom_range[1]:.2f}s")
        except ValueError as e:
            print(f"Error parsing zoom range: {e}")
            sys.exit(1)
        
        # Parse zoom location - check if it's coordinates or a named position
        if ',' in args.zoom_loc:
            # Custom coordinates: x,y,width,height
            try:
                loc_parts = [float(p.strip()) for p in args.zoom_loc.split(',')]
                if len(loc_parts) != 4:
                    print(f"Error: Custom zoom location must be 4 values: 'x,y,width,height'")
                    sys.exit(1)
                # Validate ranges
                for i, (val, name) in enumerate(zip(loc_parts, ['x', 'y', 'width', 'height'])):
                    if val < 0 or val > 1:
                        print(f"Error: {name} must be between 0 and 1 (axes coordinates)")
                        sys.exit(1)
                zoom_loc_parsed = tuple(loc_parts)
                print(f"Zoom inset at custom coordinates: x={loc_parts[0]:.2f}, y={loc_parts[1]:.2f}, "
                      f"width={loc_parts[2]:.2f}, height={loc_parts[3]:.2f}")
            except ValueError as e:
                print(f"Error parsing zoom location coordinates: {e}")
                sys.exit(1)
        else:
            # Named position - validate it
            valid_positions = ['upper right', 'upper left', 'lower right', 'lower left',
                             'center', 'center right', 'center left', 'upper center', 'lower center']
            if args.zoom_loc not in valid_positions:
                print(f"Error: Invalid zoom location '{args.zoom_loc}'")
                print(f"Valid positions: {', '.join(valid_positions)}")
                print(f"Or use custom coordinates: 'x,y,width,height'")
                sys.exit(1)
            print(f"Zoom inset at: {args.zoom_loc}")
    
    # Parse figsize if provided
    figsize = None
    if args.figsize:
        try:
            size_parts = args.figsize.split(',')
            if len(size_parts) != 2:
                print(f"Error: Figure size must be two values: 'width,height'")
                sys.exit(1)
            figsize = (float(size_parts[0].strip()), float(size_parts[1].strip()))
            if figsize[0] <= 0 or figsize[1] <= 0:
                print(f"Error: Figure dimensions must be positive")
                sys.exit(1)
            print(f"Figure size: {figsize[0]:.1f} x {figsize[1]:.1f} inches")
        except ValueError as e:
            print(f"Error parsing figure size: {e}")
            sys.exit(1)
    
    # Parse legend location if provided
    legend_loc_parsed = args.legend_loc
    if ',' in args.legend_loc:
        # Custom coordinates: x,y
        try:
            loc_parts = [float(p.strip()) for p in args.legend_loc.split(',')]
            if len(loc_parts) != 2:
                print(f"Error: Custom legend location must be 2 values: 'x,y'")
                sys.exit(1)
            # Validate ranges
            for val in loc_parts:
                if val < 0 or val > 1:
                    print(f"Error: Legend coordinates must be between 0 and 1 (axes coordinates)")
                    sys.exit(1)
            legend_loc_parsed = tuple(loc_parts)
            print(f"Legend at custom coordinates: x={loc_parts[0]:.2f}, y={loc_parts[1]:.2f}")
        except ValueError as e:
            print(f"Error parsing legend location: {e}")
            sys.exit(1)
    else:
        # Named position - validate it
        valid_positions = ['best', 'upper right', 'upper left', 'lower right', 'lower left',
                          'center', 'center right', 'center left', 'upper center', 'lower center',
                          'right', 'left']
        if args.legend_loc not in valid_positions:
            print(f"Warning: '{args.legend_loc}' may not be a valid legend location")
            print(f"Common positions: {', '.join(valid_positions)}")
    
    # Validate number of labels matches number of files
    if len(labels) != len(args.csv_files):
        print(f"Error: Number of labels ({len(labels)}) must match number of CSV files ({len(args.csv_files)})")
        print(f"CSV files: {len(args.csv_files)}")
        print(f"Labels: {labels}")
        sys.exit(1)
    
    # Create plotter and load data
    plotter = BandwidthPlotter()
    
    print("Loading CSV files...")
    print("="*80)
    
    success_count = 0
    for csv_file, label in zip(args.csv_files, labels):
        if plotter.load_csv(csv_file, label):
            success_count += 1
    
    if success_count == 0:
        print("\nError: No data could be loaded")
        sys.exit(1)
    
    if success_count < len(args.csv_files):
        print(f"\nWarning: Only {success_count}/{len(args.csv_files)} files loaded successfully")
    
    # Create plot
    print("\nCreating plot...")
    plotter.plot_combined(
        output_file=args.output,
        title=args.title,
        plot_type=args.type,
        colors=colors,
        linestyles=linestyles,
        zoom_range=zoom_range,
        zoom_loc=zoom_loc_parsed if args.zoom else args.zoom_loc,
        zoom_size=args.zoom_size,
        fontsize=args.fontsize,
        no_titles=args.no_titles,
        figsize=figsize,
        legend_loc=legend_loc_parsed,
        legend_ncol=args.legend_ncol,
        no_legend=args.no_legend,
        export_legend=args.export_legend,
        show=not args.no_plot
    )
    
    # Create comparison table if requested
    if args.table:
        print("\nCreating comparison table...")
        plotter.create_comparison_table(args.table)
    
    # Print statistics
    plotter.print_statistics()


if __name__ == '__main__':
    main()
