#!/usr/bin/env bash

run() {
	cmd=$@
	sleep 5
	echo "starting command!"
	exec $cmd
}


if [ $# -eq 0 ]; then
	>&2 echo "usage: nthr <command> <command_args>"
	exit 1
fi

if [ "$EUID" -eq 0 ]; then
	echo "Do not run me as root! I will run sudo when needed."
	exit 1
fi

cmd=$@
(run $cmd ) &
pid=$!

sudo -E $(which bpftrace) -e '

tracepoint:sched:sched_process_exec /pid == $1 && !@init/ {
	@init = 1;
}

tracepoint:sched:sched_wakeup_new /pid == $1 && @init/ {
	@cnt++;
}

tracepoint:sched:sched_process_exit /tid == $1 && @init/ {
	exit()
}

END {
	printf("%d\n", @cnt);
	clear(@cnt);
	clear(@init);
}
' $pid

wait $pid
